language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -e '(or (progn (ql:quickload :arpachat) (asdf:test-system :arpachat)) (uiop:quit -1))'
