language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros rove -e '(or (progn  (rove:run :arpachat/tests :style :spec)) (uiop:quit -1))'
