language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -e '(ql:quickload :rove)' -e '(or (rove:run :arpachat/tests) (uiop:quit -1))'
